### ISSUE TITLE
Special symbols in docker secrets

### ISSUE THREAD

**Issue by itka4yk** [RehanSaeed/Microsoft.Extensions.Configuration.DockerSecrets.Unofficial#1]
**Expected Behavior:**
docker secrets without new line character at the end after evaluating this command:
```echo "This is a secret" | docker secret create my_secret_data -```

**Actual Behavior:**
All docker secrets have new line character at the end.

**Steps to Reproduce the Problem:**

1. ```echo "This is a secret" | docker secret create my_secret_data -```
2. read that secret in startup from configuration
3. secret will have new line character at the end

**Specifications:**
- dotnet core 1.1
- MacOS

PS. Sure, we can use ```echo -n "some secret"```, but this problem appears after reading secrets from files as well (if we edit them using vim or nano).

**Comment by RehanSaeed** [comment]
Use the new official package

**Comment by RehanSaeed** [comment]
https://www.nuget.org/packages/microsoft.extensions.configuration.keyperfile/2.1.0
